from global_alignment import global_alignment

protein_sequences = {
    "human": "MTPMRKTNPLMKLINHSFIDLPTPSNISAWWNFGSLLGACLILQITTGLFLAMHYSPDASTAFSSIAHIT \
            RDVNYGWIIRYLHANGASMFFICLFLHIGRGLYYGSFLYSETWNIGIILLLATMATAFMGYVLPWGQMSF \
            WGATVITNLLSAIPYIGTDLVQWIWGGYSVDSPTLTRFFTFHFILPFIIAALATLHLLFLHETGSNNPLG \
            ITSHSDKITFHPYYTIKDALGLLLFLLSLMTLTLFSPDLLGDPDNYTLANPLNTPPHIKPEWYFLFAYTI \
            LRSVPNKLGGVLALLLSILILAMIPILHMSKQQSMMFRPLSQSLYWLLAADLLILTWIGGQPVSYPFTII \
            GQVASVLYFTTILILMPTISLIENKMLKWA",

    "tiger": "MTNIRKSHPLIKIINHSFIDLPAPSNISAWWNFGSLLGVCLILQILTGLFLAMHYTSDTMTAFSSVTHIC \
            RDVNYGWIIRYLHANGASMFFICLYMHVGRGMYYGSYTFSKTWNIGIVLLFTVMATAFMGYVLPWGQMSF \
            WGATVITNLLSAIPYIGTDLVEWIWGGFSVDKATLTRFFAFHFILPFIVSALAAVHLLFLHETGSNNPSG \
            MVSDSDKIPFHPYYTIKDILGLLVLILTLTLLVLFSPDLLGDPDNYIPANPLNTPPHIKPEWYFLFAYAI \
            LRSIPNKLGGVLALVLSILILATIPALHTSKQRGMMFRPLSQCLFWLLVADLLTLTWIGGQPVEHPFIAI \
            GQLASILYFFILLVLIPISGIIENRLLKW",
    "polar bear": "MTNIRKTHPLAKIINNSFIDLPTPSNISAWWNFGSLLGVCLILQILTGLFLAMHYTSDTTTAFSSVTHIC \
            RDVHYGWVIRYVHANGASMFFICLFMHVGRGLYYGSYLFSETWNIGIILLFTVMATAFMGYVLPWGQMSF \
            WGATVITNLLSAIPYIGTDLVEWIWGGFSVDKATLTRFFAFHFILPFIILALAAVHLLFLHETGSNNPSG \
            IPSDSDKIPFHPYYTIKDILGALLLTLALATLVLFSPDLLGDPDNYIPANPLSTPPHIKPEWYFLFAYAI \
            LRSIPNKLGGVLALIFSILILALIPLLHTSKQRGMMFRPLSQCLFWLLVADLLTLTWIGGQPVEHPFIII \
            GQLASILYFTILLVLMPIAGIIENNLLKW",
    "bottlenose dolphin": "MTNIRKTHPLMKILNDAFIDLPTPSNISSWWNFGSLLGLCLIMQILTGLFLAMHYTPDTSTAFSSVAHIC \
            RDVNYGWFIRYLHANGASMFFICLYAHIGRGLYYGSYMFQETWNIGVLLLLTVMATAFVGYVLPWGQMSF \
            WGATVITNLLSAIPYIGTTLVEWIWGGFSVDKATLTRFFAFHFILPFIITALAAVHLLFLHETGSNNPTG \
            IPSNMDMIPFHPYYTIKDILGALLLILTLLALTLFTPDLLGDPDNYTPANPLSTPAHIKPEWYFLFAYAI \
            LRSIPNKLGGVLALLLSILVLIFIPMLQTSKQRSMMFRPFSQLLFWTLIADLLTLTWIGGQPVEHPYIIV \
            GQLASILYFLLILVLMPMAGLIENKLLKW",
    "great white shark": "MALNIRKIHPLLKIMNQTLIDLPAPSNISIWWNFGSLLGLCLVIQIVTGLFLAMHYTADITMAFSSVTHI \
            CRDVNYGWLIRNIHANGASLFFVCIYFHIARGLYYGSYLYKETWNIGVILLFLLMATAFVGYVLPWGQMS \
            FWGATVITNLLSAFPYIGDTLVQWIWGGFSVDNATLTRFFAFHFLLPFLITALMIIHILFLHETGSNNPM \
            GLNSDMDKISFHPYFIYKDALGFLSLLILLGILALFLPNLLGDAENFIPANPLVTPPHIKPEWYFLFAYA \
            ILRSIPNKLGGVLALLFSILILMLVPFLHTSKQRSSTFRPLTQVFFWILVANMLVLTWIGGQPVEQPFIL \
            IGQIASISYFSLFLIAIPLAGWWENKILGLN",
    "rhesus monkey": "MTPMRKSNPILKMINRSFIDLPAPPNLSMWWNFGSLLAACLILQIITGLLLAMHYSPDTSSAFSSIAHIT \
            RDVKYGWITRYLHANGASMLFICLFLHIGRGLYYGSYLLLETWNIGIMLLLMTMTTAFMGYVLPWGQMSF \
            WGATVITNLLSAIPYIGTNLVQWIWGGYAIDSPTLTRFFTLHFILPFIIIALTTVHLLFLHETGSNNPCG \
            ISSDSDKIAFHPYYTTKDILGLVLLLFILATLTLLSPNLLNDPDNYIPADPLNTPPHIKPEWYFLFAYTI \
            LRSIPNKLGGVLALFLSILILAAIPMLHKSKQQSMMFRPLSQFLFWLLITILLTLTWIGSEPVVQPLTTI \
            GQVASMMYFITILILMPLASLIENNLLKWT",
    "orangutan": "MTSTRKTNPLMKLINHSLIDLPTPSNISAWWNFGSLLGACLIIQITTGLFLAMHYSPDASTAFSSIAHIT \
            RDVNYGWMIRHLHANGASMFFICLFLHIGRGLYYGSFTHLETWNIGIILLFTTMMTAFMGYVLPWGQMSF \
            WGATVITNLLSAIPYIGTDLVQWVWGGYSVNSPTLTRFFTLHFMLPFIITALTTLHLLFLHETGSNNPLG \
            IPSHSDKITFHPYYTIKDILGLLLFLLALMTLTLLSPDLLSDPDNYTLANPLSTPPHIKPEWYFLFAYAI \
            LRSVPNKLGGVMALMLSILILTTIPALHMSKQQSMTFRPLSQFLYWLLIADLLILTWIGGQPVSYPFITI \
            SQVASTLYFTTILLLMPASSLIENHMLKWT",
    "chimpanzee": "MTPTRKINPLMKLINHSFIDLPTPSNISAWWNFGSLLGACLILQITTGLFLAMHYSPDASTAFSSIAHIT \
            RDVNYGWIIRYLHANGASMFFICLFLHIGRGLYYGSFLYLETWNIGIILLLTTMATAFMGYVLPWGQMSF \
            WGATVITNLLSAIPYIGTDLVQWVWGGYSVDSPTLTRFFTFHFILPFIITALTTLHLLFLHETGSNNPLG \
            ITSHSDKITFHPYYTIKDILGLFLFLLILMTLTLFSPGLLGDPDNYTLANPLNTPPHIKPEWYFLFAYTI \
            LRSIPNKLGGVLALLLSILILTAIPVLHTSKQQSMMFRPLSQLLYWLLATDLLILTWIGGQPVSYPFITI \
            GQMASVLYFTTILILMPIASLIENKMLEWT",
	"golden eagle": "MAPNPRKSHPLLKMVNNSLIDLPTPSNISTWWNFGSLLGICLMTQILTGLLLAMHYTADTTLAFSSVAHT \
			CRNVQYGWLIRNLHANGASFFFICIYLHIGRGLYYGSYLYKETWNTGIILLLTLMATAFVGYVLPWGQMS \
			FWGATVITNLFSAIPYIGQTLVEWAWGGFSVDNPTLTRFFALHFLLPFLIASLTLIHLTFLHESGSNNPL \
			GIISNCDKIPFHPYFSLKDILGFVLMLLPLTTLALFSPNLLGDPENFTPANPLVTPPHIKPEWYFLFAYA \
			ILRSIPNKLGGVLALAASVLILFLIPFLHKSKQRTMTFRPLSQLLFWTLIANLLILTWIGSQPVEHPFII \
			IGQLASLTYFSTLLILFPLIGALENKMLNH",
	"peregrine falcon": "MAPNIRKSHPLVKMINNSLIDLPTPPNISMWWNFGSLLGICLATQILTGLLLAMHYTADTTLAFSSVAHT \
			CRNVQYGWLIRNLHANGASLFFICIYMHIGRGIYYGSYLYKETWNTGIILLLTLMATAFVGYVLPWGQMS \
			FWGATVITNLFSAIPYIGQTLVEWAWGGFSVDNPTLTRFFALHFLLPFLIAGLTLIHLTFLHESGSNNPL \
			GITSNCDKIPFHPYYSLKDILGFMLMYLPLMTLALFTPNLLGDPENFTPANPLVTPPHIKPEWYFLFAYA \
			ILRSIPNKLGGVLALAASVLILFLSPLLHKSKQRTMTFRPLSQSLFWLLVTNLLILTWVGSQPVEHPFII \
			IGQLASLSYFTTLLILLPLTGALENKILNY",
	"gray wolf": "MTNIRKTHPLAKIVNNSFIDLPAPSNISAWWNFGSLLGVCLILQILTGLFLAMHYTSDTATAFSSVTHIC \
			RDVNYGWIIRYMHANGASMFFICLFLHVGRGLYYGSYVFMETWNIGIVLLFATMATAFMGYVLPWGQMSF \
			WGATVITNLLSAIPYIGTDLVEWIWGGFSVDKATLTRFFAFHFILPFIIAALAMVHLLFLHETGSNNPSG \
			ITSDSDKIPFHPYYTIKDILGALLLLLILMSLVLFSPDLLGDPDNYTPANPLNTPPHIKPEWYFLFAYAI \
			LRSIPNKLGGVLALVFSILILAFIPLLHTSKQRSMMFRPLSQCLFWLLVADLLTLTWIGGQPVEHPFIII \
			GQVASILYFTILLILMPTVSVIENNLLKW",
	"african clawed frog": "MAPNIRKSHPLIKIINNSFIDLPTPSNISSLWNFGSLLGVCLIAQIITGLFLAMHYTADTSMAFSSVAHI \
			CFDVNYGLLIRNLHANGLSFFFICIYLHIGRGLYYGSFLYKETWNIGVILLFLVMATAFVGYVLPWGQMS \
			FWGATVITNLLSAKPYIGNVLVQWSLGGFSVDNATLTRFFAFHFLLPFIIAGASILHLLFLHETGSTNPT \
			GLNSDPDKVPFHPYFSYKDLLGFLIMLTALTLLAMFSPNLLGDPDNFTPANPLITPPHIKPEWYFLFAYA \
			ILRSMNKLGGVLALVLSILILALMPLLHTSKQRSLMFRPFTQIMFWALVADTLILTWIGGQPVEDPYTMI \
			GQLASVIYFSIFIIMFPLMGWVENKLLNW",
	"nile crocodile": "MTHQLRKSHPLLKLVNHSLIDLPTPSNISYWWNFGSLLGFTLLVQLASGILLMMHFLADDSLAFMSVAYT \
			SREVWYGWLIRSLHANGASLFFLCIFLHIGRGVYYGSYLNENTWNIGVLLLLLLMATAFMGYVLPWGQMS \
			FWGATVITNLMSAIPYVGNTIVTWIWGGPSVNSATLTRFTTLHFLLPFILLAAVITHLIFLHERGSFNPL \
			GLTSNADKIPFHPYFSAKDAMGMAMAAVLLTTLTFYFPNLLGDPENFTPADPMKTPDHIKPEWYFLFAYT \
			ILRCIPNKLTGVLAMFASILVLLLLPTLHTSKRQSMSLRPLSQLLFWALIADFFILTWIGGQPVQDPYIL \
			IGQVASFMYFFTILILLPLAGMIENLLIKPLRYPT",
	"indian cobra": "MSNQHVLLTSNLLPVGSNISTWWNFGSMLLACLMLQIMTGFFLAIHYTANINLAFSSVIHITRDVPYGWI \
			MQNLHTISASLFFICIYTHIARGLYYGLYLNKEVWLSGTALLVILMATAFFGYVLPWGQMSFWAATVITN \
			LLTAIPYLGITLTTWLWGGFSINDPTLTRFFALHFILPFIIISLSSVHIILLHNEGSNNPLGTNSDIDKI \
			PFHPYHSYKDMLMITSMITLLLIILSFSPNLLNDPENFSKANPLVTPQHIKPEWYFLFAYGILRSIPNKL \
			GGTLALLLSVLILTTAPFTHTSYTRSMMFRPLSQILFWTLIATFVTITWTASKPVEPPFITISQTTSIFY \
			FSFFILTPLLGWTENKMMMTNN",
	"komodo dragon": "MTHRKTNPALATLNHALINLPTPPNITLWWNFGALLGLCLGIQIITGLFLAMHYTTDISMAFSSVSHICR \
			DIQHGWLLRNLHANGASLFFLCIYIHIGRGIYHGSYLLKKTWFAGTLLLLLLMATAFMGYILPWGQMSLW \
			GATVITNLLSTIPYVGTTLVEWIWGGFSVDNATLTRFFTLHFLLPFIITATVLLHIMLLHETGSNNPTGL \
			STNSDKIPFHPYHTLKDLLQGTILILVLMLLATFTPNILSDPENFLPANPFTTPTHIKPEWYFLFAYAIL \
			RSIPNKLGGVMALLASILILLIIPNLHQSKQQTMNFRPLSQFLFWTIIANVLILTWIGGQPVEDPFILIG \
			RISSGAYFLLFLSMPFIMLTENKLLNW",
	"giant anaconda": "MPHQQILMLFGLLPVATNISTWWNFGSMLLACSTLQVLTGFFLAVHYTANINLAFSSIIHITRDVPYGWL \
			MQNLHAIGASMFFICIYIHIARGLYYGSYLNKETWLSGTMLLIMLMATAFFGYVLPWGQMSFWAATVITN \
			LLTAIPYLGNTMTTWLWGGFAINDPTLTRFFALHFILPFGIISLSSLHVILLHEEGSSNPLGTNPDIDKI \
			PFHPYHTYKDLLMLTIMTILLLLIVSFSPDIFNDPDNFSKANPLVTPQHIKPEWYFLFAYGILRSIPNKL \
			GGALALTMSIIILMTVPFTHTSKMRSMMFRPFMQMTFWMFAATFLVITWTATKPVEQPFTLIGQMASMLY \
			FLFFISNPIMGWLENKIMKT",
	"striped hyena": "MTNIRKSHPLIKIVNESFIDLPTPSNISAWWNFGSLLGICLILQILTGLFLAMHYTSDTTTAFSSVTHIC \
			RDVNYGWIIRYMHANGASMFFICLFMHAGRGMYYGSYTFSETWNIGILLLFTVMATAFMGYVLPWGQMSF \
			WGATVITNLLSAIPYIGTNLVEWIWGGFSVDKATLTRFFAFHFILPFIILALAIIHLLFLHETGSNNPSG \
			MTSDTDKIPFHPYYTIKDILGLLLLILMLMLLVLFSPDLLGDPDNYTPANPLNTPPHIKPEWYFLFAYAI \
			LRSIPNKLGGVLALILSILILAVVPLLHTSKQRGMMFRPISQCLFWLLVADLLTLTWIGGQPVEHPFITI \
			GQLASIMYFSIILILMPISGIIENHLLKW",
	"southern house mosquito": "MNKPLRKSHPLISIANNALVDLPAPSNISAWWNFGSLLGLCLVIQILTGLFLAMHYTADIETAFNSVNHI \
			YRDVNNGWFLRICHANGASFFFACLFIHVGRGVYYNSYLYIPTWMIGVIILFMVMATGFLGYVLPWGQMS \
			FWGATVITNLLSAVPYLGTDLVQWIWGGFAVDNATLTRFFTFHFILPFIVLALTMIHLLFLHQTGSNNPL \
			GLNSNVDKIPFHPYFVYKDIVGFIIFMWILIGFIWKFNYLLMDPENFIPANPLVTPVHIQPEWYFLFAYA \
			ILRSIPNKLGGVIALVLSIAILMILPFTHTSKFRGLQFYPLNQILFWNMVIVASLLTWIGARPVEDPYVL \
			TGQILTVLYFSYFIINPLMSKYWDKLLN",
	"emperor dragonfly": "MNKPLRIKHPLFKIANSALVDLPTPSNISIWWNFGSLLGLCLVIQIATGLFLAMHYTANIEMAFYSVNHI \
			CRDVNYGWLLRTLHANGASFFFICIYLHIGRNLYYGSYNYIHTWSVGVVILFLVMGTAFMGYVLPWGQMS \
			FWGATVITNLLSAIPYLGTILVQWVWGGFAVDNATLTRFFTFHFVLPFIVAAATMVHLLFLHQTGSNNPV \
			GVNSDSDKIPFHPYFSWKDIVGFLVLIMLLTLLSLINPYLLGDPDNFIPANPLVTPVHIQPEWYFLFAYA \
			ILRSIPNKLGGVIALVMSIAILFIMPLMKSNFRGLQFYPINQILFWSLVGTVLLLTWIGARPVEDPYIIT \
			GQILTVVYFSFYLIHPMMLKLWDNLLE",
	"dog": "MTNIRKTHPLAKIVNNSFIDLPAPSNISAWWNFGSLLGVCLILQILTGLFLAMHYTSDTATAFSSVTHIC \
			RDVNYGWIIRYMHANGASMFFICLFLHVGRGLYYGSYVFMETWNIGIVLLFATMATAFMGYVLPWGQMSF \
			WGATVITNLLSAIPYIGTDLVEWIWGGFSVDKATLTRFFAFHFILPFIIAALAMVHLLFLHETGSNNPSG \
			ITSDSDKIPFHPYYTIKDILGALLLLLILMSLVLFSPDLLGDPDNYTPANPLNTPPHIKPEWYFLFAYAI \
			LRSIPNKLGGVLALVFSILILAFIPLLHTSKQRSMMFRPLSQCLFWLLVADLLTLTWIGGQPVEHPFIII \
			GQVASILYFTILLILMPTVSVIENNLLKW",
	"lion": "MTNIRKSHPLVKIINHSFIDLPTPPNISAWWNFGSLLGVCLILQILTGLFLAMHYTPDTMTAFSSVTHIC \
			RDVNYGWIIRYLHANGASMFFICLYMHVGRGMYYGSYTFSETWNIGIVLLFTVMATAFMGYVLPWGQMSF \
			WGATVITNLLSAIPYIGADLVEWIWGGFSVDKATLTRFFAFHFILPFIISALAAVHLLFLHETGSNNPSG \
			MVSDSDKIPFHPYYTIKDILGLLVLILTLMLLVLFSPDLLGDPDNYTPANPLSTPPHIKPEWYFLFAYAI \
			LRSIPNKLGGVLALVLSILILAIIPALHTSKQRGLMFRPLSQCLFWFLVADLLTLTWIGGQPVEHPFITI \
			GQLASILYFSILLILMPISGIIENRLLKW"
}

results = []
max_score = None

for species in protein_sequences.keys():
    if species != "human":
        seq = protein_sequences[species]

        dp = global_alignment(protein_sequences["human"], seq, 1, 0, 0)
        score = dp[-1][-1]
        similarity = 100 * score / len(protein_sequences["human"])
        
        results.append([species, similarity])

results = sorted(results, key=lambda x : x[1])[::-1]

print ("Similarity to humans based on the cytochrome b (mitochondrion) protein sequence")
print ()
print ("Species                                 Similarity")
print ("__________________________________________________")
for a, b in results:
    print ("{:30}          {:f}".format(a, b))
